# Generated by Django 6.0.1 on 2026-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_subject_alter_task_options_topic_task_topic"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="solved_tasks",
            field=models.ManyToManyField(
                blank=True, to="tasks.task", verbose_name="Решённые задачи"
            ),
        ),
    ]
