# Generated by Django 6.0.1 on 2026-01-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_solved_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=1000, verbose_name="Рейтинг")),
                (
                    "matches_played",
                    models.IntegerField(default=0, verbose_name="Сыграно матчей"),
                ),
                ("matches_won", models.IntegerField(default=0, verbose_name="Побед")),
                (
                    "matches_lost",
                    models.IntegerField(default=0, verbose_name="Поражений"),
                ),
                (
                    "matches_drawn",
                    models.IntegerField(default=0, verbose_name="Ничьих"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
