# Generated by Django 6.0.1 on 2026-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинги"},
        ),
        migrations.AlterField(
            model_name="rating",
            name="matches_drawn",
            field=models.IntegerField(default=0, verbose_name="Ничьи"),
        ),
    ]
