# Generated by Django 6.0.1 on 2026-01-18 17:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Условие задачи"),
                ),
                ("answer", models.CharField(verbose_name="Правильный ответ")),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("Easy", "Легко"),
                            ("Medium", "Средне"),
                            ("Hard", "Трудно"),
                        ],
                        verbose_name="Уровень сложности",
                    ),
                ),
            ],
        ),
    ]
