# Generated by Django 6.0.1 on 2026-01-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_subject_alter_task_options_topic_task_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.topic",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="tasks.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
