# Generated by Django 6.0.1 on 2026-01-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_topic_alter_topic_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tip",
            field=models.TextField(blank=True, null=True, verbose_name="Подсказка"),
        ),
    ]
