# Generated by Django 6.0.1 on 2026-01-24 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0004_task_tip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PvpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название настройки"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=15, verbose_name="Длительность (минуты)"
                    ),
                ),
                (
                    "max_tasks",
                    models.IntegerField(default=5, verbose_name="Максимум задач"),
                ),
                (
                    "k_factor",
                    models.IntegerField(default=32, verbose_name="K-фактор Elo"),
                ),
                (
                    "initial_rating",
                    models.IntegerField(default=1000, verbose_name="Начальный рейтинг"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Настройки PvP",
                "verbose_name_plural": "Настройки PvP",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидание игрока"),
                            ("playing", "Идет игра"),
                            ("finished", "Завершен"),
                            ("cancelled", "Отменен"),
                            ("technical_error", "Техническая ошибка"),
                        ],
                        default="waiting",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("player1_win", "Победа игрока 1"),
                            ("player2_win", "Победа игрока 2"),
                            ("draw", "Ничья"),
                            ("technical", "Техническая ничья"),
                        ],
                        null=True,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начат"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=15, verbose_name="Длительность (минуты)"
                    ),
                ),
                (
                    "max_tasks",
                    models.IntegerField(default=5, verbose_name="Максимум задач"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
            options={
                "verbose_name": "PvP матч",
                "verbose_name_plural": "PvP матчи",
            },
        ),
        migrations.CreateModel(
            name="MatchParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_number", models.IntegerField(verbose_name="Номер игрока")),
                (
                    "tasks_solved",
                    models.IntegerField(default=0, verbose_name="Решено задач"),
                ),
                (
                    "time_taken",
                    models.FloatField(
                        default=0, verbose_name="Затрачено времени (секунды)"
                    ),
                ),
                (
                    "current_task_index",
                    models.IntegerField(
                        default=0, verbose_name="Текущий индекс задачи"
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Подключен"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="pvp.match",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник матча",
                "verbose_name_plural": "Участники матча",
                "unique_together": {("match", "user")},
            },
        ),
        migrations.CreateModel(
            name="MatchTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Порядковый номер")),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_tasks",
                        to="pvp.match",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача матча",
                "verbose_name_plural": "Задачи матча",
                "unique_together": {("match", "order")},
            },
        ),
    ]
