# Generated by Django 6.0.1 on 2026-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0003_match_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="pvpsettings",
            name="max_rating_diff_for_nodelay",
            field=models.IntegerField(
                default=200,
                verbose_name="Максимальная разница рейтинга для отсутствия задержек",
            ),
        ),
        migrations.AddField(
            model_name="pvpsettings",
            name="min_wait_time",
            field=models.IntegerField(
                default=10,
                verbose_name="Минимальное время ожидания (секунды), если задержка",
            ),
        ),
    ]
